### ISSUE TITLE
Probe template directory missing, preventing startup

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#317]
```
INFO: Selecting platform default AuthManager "io.cryostat.net.NoopAuthManager"
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Probe template directory does not exist, must be set using environment variable CRYOSTAT_PROBE_TEMPLATE_PATH
	at io.cryostat.templates.TemplatesModule.provideLocalProbeTemplateService(TemplatesModule.java:69)
	at io.cryostat.templates.TemplatesModule_ProvideLocalProbeTemplateServiceFactory.provideLocalProbeTemplateService(TemplatesModule_ProvideLocalProbeTemplateServiceFactory.java:42)
	at io.cryostat.templates.TemplatesModule_ProvideLocalProbeTemplateServiceFactory.get(TemplatesModule_ProvideLocalProbeTemplateServiceFactory.java:32)
	at io.cryostat.templates.TemplatesModule_ProvideLocalProbeTemplateServiceFactory.get(TemplatesModule_ProvideLocalProbeTemplateServiceFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.net.web.http.api.beta.ProbeTemplateUploadHandler_Factory.get(ProbeTemplateUploadHandler_Factory.java:49)
	at io.cryostat.net.web.http.api.beta.ProbeTemplateUploadHandler_Factory.get(ProbeTemplateUploadHandler_Factory.java:13)
	at dagger.internal.SetFactory.get(SetFactory.java:126)
	at dagger.internal.SetFactory.get(SetFactory.java:37)
	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
	at io.cryostat.net.web.WebModule_ProvideWebServerFactory.get(WebModule_ProvideWebServerFactory.java:50)
	at io.cryostat.net.web.WebModule_ProvideWebServerFactory.get(WebModule_ProvideWebServerFactory.java:15)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
	at io.cryostat.DaggerCryostat_Client.webServer(DaggerCryostat_Client.java:705)
	at io.cryostat.Cryostat.main(Cryostat.java:82)
Caused by: java.io.IOException: Probe template directory does not exist, must be set using environment variable CRYOSTAT_PROBE_TEMPLATE_PATH
	at io.cryostat.core.agent.LocalProbeTemplateService.<init>(LocalProbeTemplateService.java:69)
	at io.cryostat.templates.TemplatesModule.provideLocalProbeTemplateService(TemplatesModule.java:65)
	... 15 more
```

**Comment by andrewazores** [comment]
This stems from cryostatio/cryostat#731

@Josh-Matsuoka ^
