### ISSUE TITLE
Segfault possible if report options omitted

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#447]
Our sample CR includes a default of setting `reportOptions.replicas` to 0.
```yaml
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-sample
spec:
  # ...
  reportOptions:
    replicas: 0
```
This should be equivalent to leaving out the reportOptions section altogether, but results in a segfault when doing so.
```
goroutine 403 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x159cd00, 0x2521fc0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/cryostatio/cryostat-operator/internal/controllers/common/resource_definitions.NewCoreContainer(_, _, {_, _}, _, _)
	/workspace/internal/controllers/common/resource_definitions/resource_definitions.go:640 +0x61d
github.com/cryostatio/cryostat-operator/internal/controllers/common/resource_definitions.NewPodForCR(0xc000414400, 0xc000627c50?, 0xc0006dcfc0, 0xc00046f1a0, 0x4844, 0x0)
	/workspace/internal/controllers/common/resource_definitions/resource_definitions.go:240 +0x199
github.com/cryostatio/cryostat-operator/internal/controllers/common/resource_definitions.NewDeploymentForCR(0xc000414400, 0xc0004bb3b0?, 0x19ea358?, 0xc00027a1b0?, 0x19ebb20?, 0xe0?)
	/workspace/internal/controllers/common/resource_definitions/resource_definitions.go:177 +0x3c5
github.com/cryostatio/cryostat-operator/internal/controllers.(*CryostatReconciler).Reconcile(0xc0004bb3b0, {0x19ea358, 0xc00027a1b0}, {{{0xc000620660?, 0x10?}, {0xc000661640?, 0x40d787?}}})
	/workspace/internal/controllers/cryostat_controller.go:305 +0xccd
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x19ea2b0?, {0x19ea358?, 0xc00027a1b0?}, {{{0xc000620660?, 0x16b6640?}, {0xc000661640?, 0x4041f4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000a5680, {0x19ea2b0, 0xc0000fc700}, {0x15f68e0?, 0xc0002b7100?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000a5680, {0x19ea2b0, 0xc0000fc700})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:230 +0x325
```

**Comment by ebaron** [comment]
It seems as though our tests missed this because some functions modify the CR spec to set some default values. In a real cluster, these modifications are never sent to the cluster. The fake client however treats a `Status().Update()` as an `Update()`:
https://github.com/kubernetes-sigs/controller-runtime/blob/c83076e9f79258f23bcb200cf2391cf4ade939cf/pkg/client/fake/client.go#L671-L675
